bilgiler=[]
isim=(input("adınızı "))
soyad=(input(" soyadınız"))
telefonno =(input("telefon no"))
bilgiler.append(isim)
bilgiler.append(soyad)
bilgiler.append(telefonno)
#print(bilgiler)
öncüler=[]
öncü1= ("önce bir liste  tanımladım")
öncü2= ( "inputt değişkeni ile isim soyisim telefon o-no değişkenini ayarladım")
öncü3= ("elimde bilgi olmadığı için bilgiler listesine append metodu ile ekledim")
öncü4= ("en sonunda hepsini yazdırdım")
öncüler.append(öncü1)
öncüler.append(öncü2)
öncüler.append(öncü3)
öncüler.append(öncü4)
print(öncüler[0])
print(öncüler[1])
print(öncüler[3])
print(öncüler[2])